name: Generate Runbook

on:
  workflow_dispatch:

jobs:
  generate-runbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate runbook using Gemini API
        id: runbook
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Corrected curl command for Gemini API
          RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=$GEMINI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "contents": [
                {
                  "parts": [
                    {"text": "Generate a detailed Markdown runbook for an Azure WebApp CPU alert and auto-recovery workflow. The alert triggers when CPU usage goes above 10%. The auto-recovery is handled by an Azure Function that restarts the WebApp. Include symptoms, troubleshooting, auto-remediation, and logs sections."}
                  ]
                }
              ]
            }')

          echo "$RESPONSE" > response.json
          # Corrected jq extraction for Gemini API response
          # Gemini API response structure: .candidates[0].content.parts[0].text
          RUNBOOK_TEXT=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text')

          # Check if RUNBOOK_TEXT is empty or null, which might happen if the API response is not as expected
          if [ -z "$RUNBOOK_TEXT" ] || [ "$RUNBOOK_TEXT" == "null" ]; then
            echo "Error: Failed to extract runbook content from Gemini API response."
            echo "Full API response:"
            cat response.json
            exit 1
          fi

          echo "$RUNBOOK_TEXT" > RUNBOOK.md

      - name: Commit and push runbook
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add RUNBOOK.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-generated runbook"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
